"""Seed dữ liệu nhân viên mẫu — chỉ dùng trên môi trường dev/test.

Idempotent: dùng `id_number` để tránh phụ thuộc vào unique toàn cục của `employee_seq`.
"""

from datetime import date

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.encryption import encrypt, hash_sensitive
from app.services.administrative_import_service import normalize_text


def _d(s: str | None) -> date | None:
    return date.fromisoformat(s) if s else None


def _n(v: str) -> str:
    return normalize_text(v)


# Nhân viên mẫu — đa dạng trạng thái, giới tính, gồm cả cohort biến động gần đây để demo report
SAMPLE_EMPLOYEES = [
    {
        "employee_seq": 1,
        "full_name": "Nguyễn Văn An",
        "last_name": "Nguyễn",
        "first_name": "Văn An",
        "date_of_birth": "1988-03-15",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "001088123456",
        "id_issued_on": "2021-06-15",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234001",
        "personal_email": "nguyenvanan@gmail.com",
        "personal_tax_code": "8801234001",
        "start_date": "2024-01-15",
        "status": "official",
        "bank_account_number": "0001234001234",
        "bank_code": "VCB",
        "account_name": "NGUYEN VAN AN",
    },
    {
        "employee_seq": 2,
        "full_name": "Trần Thị Bình",
        "last_name": "Trần",
        "first_name": "Thị Bình",
        "date_of_birth": "1992-07-22",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "038092456789",
        "id_issued_on": "2022-01-10",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234002",
        "personal_email": "tranthibinh@gmail.com",
        "personal_tax_code": "8801234002",
        "start_date": "2024-03-01",
        "status": "official",
        "bank_account_number": "0002234001234",
        "bank_code": "BIDV",
        "account_name": "TRAN THI BINH",
    },
    {
        "employee_seq": 3,
        "full_name": "Lê Văn Cường",
        "last_name": "Lê",
        "first_name": "Văn Cường",
        "date_of_birth": "1985-11-08",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "001085654321",
        "id_issued_on": "2021-03-20",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234003",
        "personal_email": "levancuong@gmail.com",
        "personal_tax_code": "8801234003",
        "start_date": "2024-06-15",
        "status": "official",
        "bank_account_number": "0003234001234",
        "bank_code": "AGRIBANK",
        "account_name": "LE VAN CUONG",
    },
    {
        "employee_seq": 4,
        "full_name": "Phạm Thị Dung",
        "last_name": "Phạm",
        "first_name": "Thị Dung",
        "date_of_birth": "1995-02-28",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "086095789012",
        "id_issued_on": "2023-05-15",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234004",
        "personal_email": "phamthidung@gmail.com",
        "personal_tax_code": "8801234004",
        "start_date": "2024-09-01",
        "status": "official",
        "bank_account_number": "0004234001234",
        "bank_code": "TECHCOMBANK",
        "account_name": "PHAM THI DUNG",
    },
    {
        "employee_seq": 5,
        "full_name": "Hoàng Văn Em",
        "last_name": "Hoàng",
        "first_name": "Văn Em",
        "date_of_birth": "1990-09-12",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "TAY",
        "id_number": "020090345678",
        "id_issued_on": "2021-09-01",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234005",
        "personal_email": "hoangvanem@gmail.com",
        "personal_tax_code": "8801234005",
        "start_date": "2025-01-01",
        "status": "official",
        "bank_account_number": "0005234001234",
        "bank_code": "VIETINBANK",
        "account_name": "HOANG VAN EM",
    },
    {
        "employee_seq": 6,
        "full_name": "Ngô Thị Phương",
        "last_name": "Ngô",
        "first_name": "Thị Phương",
        "date_of_birth": "1994-05-18",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079094567890",
        "id_issued_on": "2022-06-20",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234006",
        "personal_email": "ngothiphuong@gmail.com",
        "personal_tax_code": "8801234006",
        "start_date": "2025-04-01",
        "status": "official",
        "bank_account_number": "0006234001234",
        "bank_code": "VCB",
        "account_name": "NGO THI PHUONG",
    },
    {
        "employee_seq": 7,
        "full_name": "Đỗ Văn Giang",
        "last_name": "Đỗ",
        "first_name": "Văn Giang",
        "date_of_birth": "1999-12-03",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "036099678901",
        "id_issued_on": "2023-12-10",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234007",
        "personal_email": "dovangiang@gmail.com",
        "personal_tax_code": None,
        "start_date": "2025-11-01",
        "status": "probation",
        "bank_account_number": "0007234001234",
        "bank_code": "BIDV",
        "account_name": "DO VAN GIANG",
    },
    {
        "employee_seq": 8,
        "full_name": "Vũ Thị Hoa",
        "last_name": "Vũ",
        "first_name": "Thị Hoa",
        "date_of_birth": "2001-04-25",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "001201789012",
        "id_issued_on": "2023-04-30",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234008",
        "personal_email": "vuthihoa@gmail.com",
        "personal_tax_code": None,
        "start_date": "2026-03-01",
        "status": "probation",
        "bank_account_number": "0008234001234",
        "bank_code": "AGRIBANK",
        "account_name": "VU THI HOA",
    },
    {
        "employee_seq": 9,
        "full_name": "Bùi Văn Ích",
        "last_name": "Bùi",
        "first_name": "Văn Ích",
        "date_of_birth": "1998-08-10",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "051098890123",
        "id_issued_on": "2022-08-15",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234009",
        "personal_email": "buivanych@gmail.com",
        "personal_tax_code": None,
        "start_date": "2026-04-15",
        "status": "probation",
        "bank_account_number": "0009234001234",
        "bank_code": "TECHCOMBANK",
        "account_name": "BUI VAN ICH",
    },
    {
        "employee_seq": 10,
        "full_name": "Trịnh Thị Kim",
        "last_name": "Trịnh",
        "first_name": "Thị Kim",
        "date_of_birth": "1987-06-30",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "025087901234",
        "id_issued_on": "2021-07-05",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234010",
        "personal_email": "trinhthikim@gmail.com",
        "personal_tax_code": "8801234010",
        "start_date": "2023-06-01",
        "status": "resigned",
        "resigned_date": "2025-12-31",
        "resigned_reason_type": "2",
        "resigned_reason_note": "Tìm kiếm cơ hội thu nhập tốt hơn",
        "bank_account_number": "0010234001234",
        "bank_code": "VCB",
        "account_name": "TRINH THI KIM",
    },
    {
        "employee_seq": 11,
        "full_name": "Phan Văn Lộc",
        "last_name": "Phan",
        "first_name": "Văn Lộc",
        "date_of_birth": "1964-06-15",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079064111111",
        "id_issued_on": "2021-01-12",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234011",
        "personal_email": "phanvanloc@gmail.com",
        "personal_tax_code": "8801234011",
        "start_date": "2012-05-10",
        "status": "official",
        "bank_account_number": "0011234001234",
        "bank_code": "BIDV",
        "account_name": "PHAN VAN LOC",
    },
    {
        "employee_seq": 12,
        "full_name": "Lý Thị Mai",
        "last_name": "Lý",
        "first_name": "Thị Mai",
        "date_of_birth": "1968-11-20",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "TAY",
        "id_number": "019068222222",
        "id_issued_on": "2021-02-18",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234012",
        "personal_email": "lythimai@gmail.com",
        "personal_tax_code": "8801234012",
        "start_date": "2014-08-01",
        "status": "official",
        "bank_account_number": "0012234001234",
        "bank_code": "VCB",
        "account_name": "LY THI MAI",
    },
    {
        "employee_seq": 13,
        "full_name": "Tạ Thị Sen",
        "last_name": "Tạ",
        "first_name": "Thị Sen",
        "date_of_birth": "1967-02-09",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079067333333",
        "id_issued_on": "2021-03-22",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234013",
        "personal_email": "tathisen@gmail.com",
        "personal_tax_code": "8801234013",
        "start_date": "2010-03-15",
        "status": "official",
        "bank_account_number": "0013234001234",
        "bank_code": "AGRIBANK",
        "account_name": "TA THI SEN",
    },
    {
        "employee_seq": 14,
        "full_name": "Tạ Quốc Minh",
        "last_name": "Tạ",
        "first_name": "Quốc Minh",
        "date_of_birth": "1986-04-18",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079086444444",
        "id_issued_on": "2021-05-11",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234014",
        "personal_email": "taquocminh.ks@gmail.com",
        "personal_tax_code": "8801234014",
        "start_date": "2022-01-10",
        "status": "official",
        "bank_account_number": "0014234001234",
        "bank_code": "VCB",
        "account_name": "TA QUOC MINH",
    },
    {
        "employee_seq": 15,
        "full_name": "Nguyễn Thị Lan",
        "last_name": "Nguyễn",
        "first_name": "Thị Lan",
        "date_of_birth": "1991-09-03",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079091555555",
        "id_issued_on": "2022-02-14",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234015",
        "personal_email": "nguyenthilan.ksnb@gmail.com",
        "personal_tax_code": "8801234015",
        "start_date": "2022-03-01",
        "status": "official",
        "bank_account_number": "0015234001234",
        "bank_code": "BIDV",
        "account_name": "NGUYEN THI LAN",
    },
    {
        "employee_seq": 16,
        "full_name": "Phạm Đức Hòa",
        "last_name": "Phạm",
        "first_name": "Đức Hòa",
        "date_of_birth": "1993-12-12",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079093666666",
        "id_issued_on": "2022-06-08",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234016",
        "personal_email": "phamduchoa.ksnb@gmail.com",
        "personal_tax_code": "8801234016",
        "start_date": "2022-06-15",
        "status": "official",
        "bank_account_number": "0016234001234",
        "bank_code": "AGRIBANK",
        "account_name": "PHAM DUC HOA",
    },
    {
        "employee_seq": 17,
        "full_name": "Lê Minh Trang",
        "last_name": "Lê",
        "first_name": "Minh Trang",
        "date_of_birth": "1994-01-25",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079094777777",
        "id_issued_on": "2022-08-19",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234017",
        "personal_email": "leminhtrang.it@gmail.com",
        "personal_tax_code": "8801234017",
        "start_date": "2023-02-06",
        "status": "official",
        "bank_account_number": "0017234001234",
        "bank_code": "TECHCOMBANK",
        "account_name": "LE MINH TRANG",
    },
    {
        "employee_seq": 18,
        "full_name": "Vũ Hoàng Sơn",
        "last_name": "Vũ",
        "first_name": "Hoàng Sơn",
        "date_of_birth": "1996-07-07",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079096888888",
        "id_issued_on": "2023-01-17",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234018",
        "personal_email": "vuhoangson.it@gmail.com",
        "personal_tax_code": "8801234018",
        "start_date": "2023-05-08",
        "status": "official",
        "bank_account_number": "0018234001234",
        "bank_code": "VIETINBANK",
        "account_name": "VU HOANG SON",
    },
    {
        "employee_seq": 19,
        "full_name": "Đặng Văn Nam",
        "last_name": "Đặng",
        "first_name": "Văn Nam",
        "date_of_birth": "1996-02-14",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079096999991",
        "id_issued_on": "2022-03-20",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234019",
        "personal_email": "dangvannam@gmail.com",
        "personal_tax_code": "8801234019",
        "start_date": "2026-01-08",
        "status": "official",
        "bank_account_number": "0019234001234",
        "bank_code": "VCB",
        "account_name": "DANG VAN NAM",
    },
    {
        "employee_seq": 20,
        "full_name": "Đinh Thị Oanh",
        "last_name": "Đinh",
        "first_name": "Thị Oanh",
        "date_of_birth": "1997-05-21",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079097999992",
        "id_issued_on": "2022-04-18",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234020",
        "personal_email": "dinhthioanh@gmail.com",
        "personal_tax_code": "8801234020",
        "start_date": "2026-03-05",
        "status": "official",
        "bank_account_number": "0020234001234",
        "bank_code": "BIDV",
        "account_name": "DINH THI OANH",
    },
    {
        "employee_seq": 21,
        "full_name": "Lưu Quốc Phong",
        "last_name": "Lưu",
        "first_name": "Quốc Phong",
        "date_of_birth": "1994-10-11",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079094999993",
        "id_issued_on": "2021-09-09",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234021",
        "personal_email": "luuquocphong@gmail.com",
        "personal_tax_code": "8801234021",
        "start_date": "2026-03-18",
        "status": "official",
        "bank_account_number": "0021234001234",
        "bank_code": "AGRIBANK",
        "account_name": "LUU QUOC PHONG",
    },
    {
        "employee_seq": 22,
        "full_name": "Mai Thị Quỳnh",
        "last_name": "Mai",
        "first_name": "Thị Quỳnh",
        "date_of_birth": "1998-07-30",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079098999994",
        "id_issued_on": "2023-01-13",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234022",
        "personal_email": "maithiquynh@gmail.com",
        "personal_tax_code": "8801234022",
        "start_date": "2026-06-03",
        "status": "official",
        "bank_account_number": "0022234001234",
        "bank_code": "TECHCOMBANK",
        "account_name": "MAI THI QUYNH",
    },
    {
        "employee_seq": 23,
        "full_name": "Nghiêm Văn Sơn",
        "last_name": "Nghiêm",
        "first_name": "Văn Sơn",
        "date_of_birth": "1995-12-08",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079095999995",
        "id_issued_on": "2022-10-27",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234023",
        "personal_email": "nghiemvanson@gmail.com",
        "personal_tax_code": "8801234023",
        "start_date": "2026-06-12",
        "status": "official",
        "bank_account_number": "0023234001234",
        "bank_code": "VIETINBANK",
        "account_name": "NGHIEM VAN SON",
    },
    {
        "employee_seq": 24,
        "full_name": "Phùng Thị Trúc",
        "last_name": "Phùng",
        "first_name": "Thị Trúc",
        "date_of_birth": "1999-03-17",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079099999996",
        "id_issued_on": "2023-02-22",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234024",
        "personal_email": "phungthitruc@gmail.com",
        "personal_tax_code": "8801234024",
        "start_date": "2026-09-02",
        "status": "official",
        "bank_account_number": "0024234001234",
        "bank_code": "VCB",
        "account_name": "PHUNG THI TRUC",
    },
    {
        "employee_seq": 25,
        "full_name": "Quách Thu Uyên",
        "last_name": "Quách",
        "first_name": "Thu Uyên",
        "date_of_birth": "1992-08-25",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079092999997",
        "id_issued_on": "2021-11-04",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234025",
        "personal_email": "quachthuyuyen@gmail.com",
        "personal_tax_code": "8801234025",
        "start_date": "2024-07-15",
        "status": "resigned",
        "resigned_date": "2026-02-14",
        "resigned_reason_type": "2",
        "resigned_reason_note": "Chuyển nơi sinh sống",
        "bank_account_number": "0025234001234",
        "bank_code": "BIDV",
        "account_name": "QUACH THU UYEN",
    },
    {
        "employee_seq": 26,
        "full_name": "Tôn Văn Vượng",
        "last_name": "Tôn",
        "first_name": "Văn Vượng",
        "date_of_birth": "1990-01-09",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079090999998",
        "id_issued_on": "2020-12-16",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234026",
        "personal_email": "tonvanvuong@gmail.com",
        "personal_tax_code": "8801234026",
        "start_date": "2023-03-01",
        "status": "resigned",
        "resigned_date": "2026-05-06",
        "resigned_reason_type": "1",
        "resigned_reason_note": "Thay đổi định hướng nghề nghiệp",
        "bank_account_number": "0026234001234",
        "bank_code": "AGRIBANK",
        "account_name": "TON VAN VUONG",
    },
    {
        "employee_seq": 27,
        "full_name": "Ưng Thị Vân",
        "last_name": "Ưng",
        "first_name": "Thị Vân",
        "date_of_birth": "1996-06-06",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079096999999",
        "id_issued_on": "2022-07-12",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234027",
        "personal_email": "ungthivan@gmail.com",
        "personal_tax_code": "8801234027",
        "start_date": "2024-11-20",
        "status": "resigned",
        "resigned_date": "2026-05-28",
        "resigned_reason_type": "2",
        "resigned_reason_note": "Nhận công việc mới",
        "bank_account_number": "0027234001234",
        "bank_code": "TECHCOMBANK",
        "account_name": "UNG THI VAN",
    },
    {
        "employee_seq": 28,
        "full_name": "Vi Văn Xuân",
        "last_name": "Vi",
        "first_name": "Văn Xuân",
        "date_of_birth": "1989-09-19",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "TAY",
        "id_number": "079089999900",
        "id_issued_on": "2021-08-23",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234028",
        "personal_email": "vivanxuan@gmail.com",
        "personal_tax_code": "8801234028",
        "start_date": "2022-06-10",
        "status": "resigned",
        "resigned_date": "2026-08-09",
        "resigned_reason_type": "3",
        "resigned_reason_note": "Nghỉ để chăm sóc gia đình",
        "bank_account_number": "0028234001234",
        "bank_code": "VIETINBANK",
        "account_name": "VI VAN XUAN",
    },
    {
        "employee_seq": 29,
        "full_name": "Xa Văn Yên",
        "last_name": "Xa",
        "first_name": "Văn Yên",
        "date_of_birth": "1997-11-28",
        "gender": "male",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079097999901",
        "id_issued_on": "2023-03-18",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234029",
        "personal_email": "xavanyen@gmail.com",
        "personal_tax_code": "8801234029",
        "start_date": "2026-11-11",
        "status": "official",
        "bank_account_number": "0029234001234",
        "bank_code": "VCB",
        "account_name": "XA VAN YEN",
    },
    {
        "employee_seq": 30,
        "full_name": "Y Trinh",
        "last_name": "Y",
        "first_name": "Trinh",
        "date_of_birth": "1991-04-04",
        "gender": "female",
        "nationality_code": "VN",
        "ethnicity_code": "KINH",
        "id_number": "079091999902",
        "id_issued_on": "2021-06-14",
        "id_issued_by": "Cục Cảnh sát ĐKQLCƯ và DLQGVDC",
        "phone_number": "0901234030",
        "personal_email": "ytrinh@gmail.com",
        "personal_tax_code": "8801234030",
        "start_date": "2024-01-22",
        "status": "resigned",
        "resigned_date": "2026-12-19",
        "resigned_reason_type": "1",
        "resigned_reason_note": "Chuyển công tác",
        "bank_account_number": "0030234001234",
        "bank_code": "BIDV",
        "account_name": "Y TRINH",
    },
]


async def seed_sample_employees(session: AsyncSession) -> int:
    """Seed nhân viên mẫu. Idempotent — bỏ qua nếu id_number đã tồn tại."""
    added = 0
    for emp in SAMPLE_EMPLOYEES:
        result = await session.execute(
            text("""
                INSERT INTO employees (
                    employee_seq, employee_code_sequence_id, full_name, normalized_name, last_name, first_name,
                    date_of_birth, gender, nationality_id, ethnicity_id,
                    id_number, id_number_hash, id_issued_on, id_issued_by,
                    phone_number, personal_email, personal_tax_code,
                    status, start_date, resigned_date,
                    resigned_reason_type, resigned_reason_note,
                    is_active, created_at
                )
                SELECT
                    :employee_seq,
                    (SELECT id FROM employee_code_sequences WHERE code = :employee_code_sequence_code),
                    :full_name, :normalized_name, :last_name, :first_name,
                    :date_of_birth, :gender,
                    (SELECT id FROM nationalities WHERE code = :nationality_code),
                    (SELECT id FROM ethnicities WHERE code = :ethnicity_code),
                    :id_number, :id_number_hash, :id_issued_on, :id_issued_by,
                    :phone_number, :personal_email, :personal_tax_code,
                    :status, :start_date, :resigned_date,
                    :resigned_reason_type, :resigned_reason_note,
                    :is_active, now()
                ON CONFLICT (id_number_hash) DO NOTHING
            """),
            {
                "employee_seq": emp["employee_seq"],
                "employee_code_sequence_code": emp.get("employee_code_sequence_code", "SYS1"),
                "full_name": emp["full_name"],
                "normalized_name": _n(emp["full_name"]),
                "last_name": emp["last_name"],
                "first_name": emp["first_name"],
                "date_of_birth": _d(emp["date_of_birth"]),
                "gender": emp["gender"],
                "nationality_code": emp["nationality_code"],
                "ethnicity_code": emp["ethnicity_code"],
                "id_number": encrypt(emp["id_number"]),
                "id_number_hash": hash_sensitive(emp["id_number"]),
                "id_issued_on": _d(emp["id_issued_on"]),
                "id_issued_by": emp["id_issued_by"],
                "phone_number": emp.get("phone_number"),
                "personal_email": emp.get("personal_email"),
                "personal_tax_code": encrypt(emp.get("personal_tax_code")),
                "status": emp["status"],
                "start_date": _d(emp["start_date"]),
                "resigned_date": _d(emp.get("resigned_date")),
                "resigned_reason_type": emp.get("resigned_reason_type"),
                "resigned_reason_note": emp.get("resigned_reason_note"),
                "is_active": emp["status"] != "resigned",
            },
        )
        added += result.rowcount

        # Thêm tài khoản ngân hàng nếu employee vừa được insert
        if result.rowcount > 0:
            await session.execute(
                text("""
                    INSERT INTO employee_bank_accounts (
                        employee_id, bank_id, account_number, account_name, is_primary, is_active, created_at
                    )
                    SELECT
                        e.id,
                        (SELECT id FROM banks WHERE code = :bank_code),
                        :account_number, :account_name, true, true, now()
                    FROM employees e WHERE e.id_number_hash = :id_number_hash
                    ON CONFLICT DO NOTHING
                """),
                {
                    "id_number_hash": hash_sensitive(emp["id_number"]),
                    "bank_code": emp["bank_code"],
                    "account_number": encrypt(emp["bank_account_number"]),
                    "account_name": emp["account_name"],
                },
            )

    # Sync next_value to max(employee_seq)+1 so allocate_employee_seq doesn't collide
    await session.execute(text("""
        UPDATE employee_code_sequences ecs
        SET next_value = sub.max_seq + 1
        FROM (
            SELECT employee_code_sequence_id, MAX(employee_seq) AS max_seq
            FROM employees
            GROUP BY employee_code_sequence_id
        ) sub
        WHERE ecs.id = sub.employee_code_sequence_id
          AND ecs.next_value <= sub.max_seq
    """))

    sample_hashes = [hash_sensitive(emp["id_number"]) for emp in SAMPLE_EMPLOYEES]
    await session.execute(
        text(
            """
            UPDATE employees
            SET is_active = CASE WHEN status = 'resigned' THEN FALSE ELSE is_active END
            WHERE id_number_hash = ANY(:sample_hashes)
            """
        ),
        {"sample_hashes": sample_hashes},
    )

    return added
